"""Explicit official Images API adapter; generated bytes have no presentation authority."""
from dataclasses import dataclass
import base64
import binascii

import httpx
from pydantic import SecretStr

from mira.application.ports.media import GeneratedImage, MediaRequest
from ._openai_http import (
    IMAGE_ENDPOINT, MODEL_PATTERN, PNG_SIGNATURE, ImageProviderError, OpenAIJSONTransport,
    validate_request,
)


@dataclass(frozen=True, slots=True)
class OpenAIImageOptions:
    # No default model or quality: both are part of the operator's separate spending choice.
    model: str
    quality: str

    def __post_init__(self):
        if (type(self.model) is not str or not MODEL_PATTERN.fullmatch(self.model)
                or not self.model.startswith('gpt-image-')):
            raise ValueError('image_model_invalid')
        if self.quality not in ('low', 'medium', 'high'):
            raise ValueError('image_quality_invalid')


class OpenAIImageBackend:
    def __init__(self, *, api_key: SecretStr, options: OpenAIImageOptions,
                 transport: httpx.AsyncBaseTransport | None = None,
                 timeout_seconds: float = 90.0, max_wire_bytes: int = 12_000_000):
        if not isinstance(options, OpenAIImageOptions):
            raise ValueError('image_options_required')
        self.options = options
        self._http = OpenAIJSONTransport(api_key=api_key, endpoint=IMAGE_ENDPOINT,
            transport=transport, timeout_seconds=timeout_seconds, max_wire_bytes=max_wire_bytes)

    async def generate(self, request: MediaRequest) -> GeneratedImage:
        validate_request(request)
        fence = self._http.start()
        body = await self._http.post({
            'model': self.options.model, 'prompt': request.specification,
            'n': 1, 'size': '1024x1024', 'quality': self.options.quality,
            'output_format': 'png', 'background': 'opaque', 'stream': False,
        }, max_request_bytes=32_768, fence=fence)
        fence.check()
        if (body.get('error') is not None or body.get('refusal') is not None
                or body.get('status', 'completed') != 'completed'
                or body.get('output_format', 'png') != 'png'
                or body.get('size', '1024x1024') != '1024x1024'):
            raise ImageProviderError('image_generation_incomplete')
        items = body.get('data')
        if type(items) is not list or len(items) != 1 or type(items[0]) is not dict:
            raise ImageProviderError('image_generation_count')
        item = items[0]
        if item.get('url') is not None or item.get('refusal') is not None or item.get('error') is not None:
            raise ImageProviderError('image_generation_resource')
        encoded = item.get('b64_json')
        limit = 4 * ((request.max_output_bytes + 2) // 3)
        if type(encoded) is not str or not encoded or len(encoded) > limit:
            raise ImageProviderError('image_base64_limit')
        try:
            data = base64.b64decode(encoded, validate=True)
        except (ValueError, binascii.Error):
            raise ImageProviderError('image_base64_invalid') from None
        if (not data or len(data) > request.max_output_bytes
                or not data.startswith(PNG_SIGNATURE)):
            raise ImageProviderError('image_generation_bytes')
        usage = body.get('usage')
        units = None
        if usage is not None:
            if type(usage) is not dict:
                raise ImageProviderError('image_usage_invalid')
            units = usage.get('total_tokens')
            if units is not None and (type(units) is not int or not 0 <= units <= 1_000_000_000):
                raise ImageProviderError('image_usage_invalid')
        # No provider URL, revised prompt or self-reported success becomes resource identity.
        fence.check()
        return GeneratedImage(data, 'image/png', 'openai_api', self.options.model, units)
