import test from 'node:test';
import assert from 'node:assert/strict';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
const dist=pathToFileURL(resolve(process.env.MIRA_TEST_WEB_DIST??'apps/web/dist')+'/').href;
const {BrowserAudioTransport}=await import(new URL('features/session/audio-transport.js',dist));
const {ContinuousListeningController}=await import(new URL('features/session/continuous-listening.js',dist));
const id=n=>`${String(n).padStart(8,'0')}-1234-4234-8234-123456789012`,lease=id(1);
const flush=async()=>{for(let i=0;i<16;i++)await Promise.resolve();};
const ready=(extra={})=>({type:'ready',lease_id:lease,sample_rate_hz:16000,max_seconds:null,max_samples:null,max_utterances:null,max_streams_per_session:null,max_total_streams:null,max_recognition_streams:null,session_lease_starts_used:1000001,total_lease_starts_used:1000001,stt_requests_used:1,stt_requests_remaining:9,endpoint_mode:'google_vad_offsets_natural',manual_commit_required:false,client_endpoint_supported:true,client_silence_ms:700,...extra});
class Socket{readyState=0;bufferedAmount=0;sent=[];send(s){this.sent.push(JSON.parse(s));}close(){this.readyState=3;}open(){this.readyState=1;this.onopen?.({});}message(v){this.onmessage?.({data:JSON.stringify(v)});}}
function wire(extra={}){const socket=new Socket(),events=[],errors=[],timers=new Map();let time=0,tid=0,opens=0;
 const api=new BrowserAudioTransport({apiBase:'/api/v1'},()=>({sessionId:'s',token:'synthetic'}),{baseUrl:'https://mira.test/',createSocket:()=>{opens++;return socket;},now:()=>time,setTimeout:(fn,ms)=>{const n=++tid;timers.set(n,{fn,ms});return n;},clearTimeout:n=>timers.delete(n)});
 const stream=api.continuousListening(lease,new AbortController().signal,{onEvent:e=>events.push(e),onError:e=>errors.push(e)},'natural');socket.open();socket.message(ready(extra));
 return{api,socket,stream,events,errors,timers,get opens(){return opens;},tick:ms=>{time+=ms;},pcm:(n,frames=1600)=>stream.send({sequence:n,startSample:n*frames,endSample:(n+1)*frames,pcm16le:new Uint8Array(frames*2),sampleRate:16000,channels:1})};}
function controller(extra={}){let observer,next=10000,commit=0,open=0;const inputs=[],views=[];
 const c=new ContinuousListeningController({mode:'natural',createId:()=>id(next++),createCapture:o=>({start(){o.onState('recording');return Promise.resolve(true);},stop(){},async close(){}}),openStream:(l,s,o)=>{open++;observer=o;return{ready:Promise.resolve(ready({lease_id:l,...extra.ready})),closed:new Promise(()=>{}),send(){},commit:async(cid,rev,uid)=>extra.reject?{type:'commit_rejected',lease_id:l,commit_id:cid,current_revision:rev,reason:extra.reject}:{type:'commit_ready',lease_id:l,commit_id:cid,revision:rev,utterance_id:uid,segment_seq:++commit,text:`words ${rev}`},hold:async()=>{},stop:async()=>{},cancel(){}};},submitInput:async(text,cid)=>{inputs.push({text,cid});return extra.outcome??{status:'submitted'};},interruptReply:()=>true,isPlaybackBusy:()=>false,onUpdate:v=>views.push(v)});
 return{c,views,inputs,get opens(){return open;},emit:e=>observer.onEvent({...e,lease_id:c.run?.leaseId??views.at(-1).ready.lease_id}),proof:n=>observer.onEvent({type:'utterance_ready',lease_id:c.run.leaseId,utterance_id:id(n+20000),revision:n,text:`words ${n}`,begin_offset_samples:(n-1)*20000,end_offset_samples:n*20000,source_end_sample:n*20000,final_offset_samples:n*20000,endpoint_basis:'offset_coverage'})};}
test('compiled transport accepts null limits beyond 120 seconds and 12 commits with finite service budgets',async()=>{const h=wire();try{await h.stream.ready;assert.equal([...h.timers.values()].some(t=>t.ms===0||t.ms===120000),false);for(let n=0;n<1300;n++){h.tick(100);h.pcm(n);}assert.equal(h.socket.sent.filter(f=>f.type==='audio').length,1300);for(let n=1;n<=80;n++){const p=h.stream.commit(id(n+10),10000+n);h.socket.message({type:'commit_ready',lease_id:lease,commit_id:id(n+10),segment_seq:n,revision:10000+n,text:'accepted'});assert.equal((await p).segment_seq,n);}h.socket.message({type:'recognition_status',lease_id:lease,stream_index:40,state:'listening',stt_requests_used:10,stt_requests_remaining:0});assert.equal(h.events.at(-1).stream_index,40);assert.equal(h.events.at(-1).stt_requests_remaining,0);assert.deepEqual(h.errors,[]);}finally{h.api.close();}});
test('compiled controller bounds settled history and fences old revision and source after 160 commits',async()=>{const h=controller({ready:{client_endpoint_supported:false}});h.c.start();await flush();for(let n=1;n<=160;n++){h.proof(n);await flush();}assert.equal(h.inputs.length,160);assert.equal(h.c.active,true);assert.ok(h.views.at(-1).sent_text.length<=64);assert.ok(h.c.run.automaticAttempts.size<=64);h.proof(1);h.proof(160);await flush();assert.equal(h.inputs.length,160);assert.equal(h.views.at(-1).retired_sent_text,96);await h.c.stop();});
test('service exhaustion keeps draft and accepted text and blocks lease reset',async()=>{const h=controller({ready:{client_endpoint_supported:false}});h.c.start();await flush();h.proof(1);await flush();h.emit({type:'transcript',revision:2,text:'unsent draft',is_final:true});h.emit({type:'stopped',reason:'service_budget_exhausted'});await flush();assert.equal(h.c.active,false);assert.equal(h.views.at(-1).service_budget_exhausted,true);assert.equal(h.c.start(),false);assert.equal(h.opens,1);assert.equal(h.inputs.length,1);assert.ok(h.views.at(-1).previous_previews.some(p=>p.text==='unsent draft'));assert.equal(h.views.at(-1).sent_text[0].text,'words 1');});
test('pending capacity keeps the live lease and exact draft without automatic retry',async()=>{const h=controller({ready:{client_endpoint_supported:false},reject:'pending_capacity'});h.c.start();await flush();h.proof(1);await flush();assert.equal(h.c.active,true);assert.equal(h.views.at(-1).transcript.text,'words 1');assert.equal(h.views.at(-1).transcript.can_send,true);assert.match(h.views.at(-1).notice,/待处理|稍后/);assert.equal(h.inputs.length,0);h.proof(1);await flush();assert.equal(h.inputs.length,0);await h.c.stop();});
test('unresolved records backpressure before growth and preserve every unsent text',async()=>{const h=controller({ready:{client_endpoint_supported:false},outcome:{status:'not-sent'}});h.c.start();await flush();for(let n=1;n<=65;n++){if(h.c.active){h.proof(n);await flush();}}assert.equal(h.inputs.length,64);assert.equal(h.c.active,false);assert.equal(h.views.at(-1).sent_text.length,64);assert.ok(h.views.at(-1).sent_text.every(p=>p.state==='not_sent'));assert.ok(h.views.at(-1).previous_previews.some(p=>p.text==='words 65'));assert.equal(h.c.start(),false);assert.equal(h.c.restoreSentText(h.views.at(-1).sent_text[0].commit_id),'words 1');assert.equal(h.c.start(),true);await h.c.stop();});
test('transport retires settled endpoint and hold history while fencing expired requests',async()=>{const h=wire();try{await h.stream.ready;for(let n=0;n<140;n++){h.tick(100);h.pcm(n);const ep=id(1000+n),source=(n+1)*1600;h.stream.endpoint(ep,source);h.socket.message({type:'endpoint_status',lease_id:lease,endpoint_id:ep,source_end_sample:source,state:'completed'});const p=h.stream.hold(id(2000+n),n+1),result={type:'utterance_held',lease_id:lease,utterance_id:id(2000+n),revision:n+1,text:'held'};h.socket.message(result);assert.deepEqual(await p,result);}assert.throws(()=>h.stream.endpoint(id(1000),1600));await assert.rejects(h.stream.hold(id(2000),1));assert.deepEqual(h.errors,[]);}finally{h.api.close();}});
test('finite defaults remain and Stop discards queued audio idempotently',async()=>{const h=wire({max_seconds:120,max_samples:1920000,max_utterances:12,max_streams_per_session:4,max_total_streams:8,max_recognition_streams:4,session_lease_starts_used:1,total_lease_starts_used:1});try{await h.stream.ready;assert.ok([...h.timers.values()].some(t=>t.ms===120000));for(let n=0;n<8;n++)h.pcm(n);const before=h.socket.sent.filter(f=>f.type==='audio').length,stop=h.stream.stop();h.stream.stop();for(const timer of [...h.timers.values()])timer.fn();await stop;assert.equal(h.socket.sent.filter(f=>f.type==='stop').length,1);assert.equal(h.socket.sent.filter(f=>f.type==='audio').length,before);assert.throws(()=>h.pcm(8));}finally{h.api.close();}});
test('an accepted commit racing service exhaustion still submits once, while explicit Stop fences it',async t=>{for(const reason of ['service_budget_exhausted','user_stop'])await t.test(reason,async()=>{const h=controller({ready:{client_endpoint_supported:false}});h.c.start();await flush();h.proof(1);h.emit({type:'stopped',reason});await flush();assert.equal(h.inputs.length,reason==='service_budget_exhausted'?1:0);assert.equal(h.opens,1);assert.equal(h.c.active,false);});});
test('a newer revision of retired source cannot become a new automatic input',async()=>{const h=controller({ready:{client_endpoint_supported:false}});h.c.start();await flush();for(let n=1;n<=80;n++){h.proof(n);await flush();}h.emit({type:'utterance_ready',utterance_id:id(20001),revision:999,text:'old revised words',begin_offset_samples:0,end_offset_samples:20000,source_end_sample:20000,final_offset_samples:20000,endpoint_basis:'offset_coverage'});await flush();assert.equal(h.inputs.length,80);assert.equal(h.views.at(-1).transcript.review_required,true);await h.c.stop();});
test('transport accepts pending capacity and service exhaustion as closed wire reasons without reconnect',async()=>{const h=wire();try{await h.stream.ready;const p=h.stream.commit(id(51),10001);h.socket.message({type:'commit_rejected',lease_id:lease,commit_id:id(51),current_revision:10001,reason:'pending_capacity'});assert.equal((await p).reason,'pending_capacity');h.socket.message({type:'transcript',lease_id:lease,revision:10002,text:'retained draft',is_final:true});h.socket.message({type:'stopped',lease_id:lease,reason:'service_budget_exhausted'});await h.stream.closed;assert.equal(h.events.at(-1).reason,'service_budget_exhausted');assert.equal(h.opens,1);assert.deepEqual(h.errors,[]);await assert.rejects(h.stream.commit(id(52),10002));}finally{h.api.close();}});


test('compiled wire admits hundreds of shared STT attempts with genuine null remainder',async()=>{
 const h=wire({stt_requests_used:300,stt_requests_remaining:null});
 try {await h.stream.ready;for(let n=301;n<=620;n++)h.socket.message({type:'recognition_status',lease_id:lease,stream_index:n,state:'listening',stt_requests_used:n,stt_requests_remaining:null});assert.equal(h.events.at(-1).stt_requests_used,620);assert.equal(h.events.at(-1).stt_requests_remaining,null);assert.deepEqual(h.errors,[]);assert.equal(h.opens,1);}finally{h.api.close();}
});
