import test from 'node:test';
import assert from 'node:assert/strict';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
const dist=process.env.MIRA_TEST_WEB_DIST?pathToFileURL(resolve(process.env.MIRA_TEST_WEB_DIST)+'/').href:new URL('../../apps/web/dist/',import.meta.url).href;
const {CancelSafePlayback}=await import(new URL('features/audio/playback.js',dist));
const {SessionController}=await import(new URL('features/session/controller.js',dist));
const tick=()=>new Promise(resolve=>setImmediate(resolve));
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
const voice={speech_enabled:true,microphone_enabled:true,speech_sample_rate_hz:24000,microphone_sample_rate_hz:16000,qualification:'injected_unverified',generation_mode:'mock'};
function harness(options={}){
 const calls=[],received=[],progress=[],errors=[],phases=[],microphones=[],previews=[],timings=[];let client,rev=0,activity=0,inputEpoch=0;
 const session=(overrides={})=>({schema_version:'0.1.0-foundation',session_id:'s',client_instance_id:client,revision:++rev,activity_seq:activity,input_epoch:inputEpoch,output_epoch:activity,permit_revision:rev,phase:'stopped',request_id:null,sealed:true,active_grants:[],presented_effects:[],audio_progress:[],last_error:null,...overrides});
 const api={create:async c=>{client=c;return {session:session(),session_token:'secret'};},capabilities:async()=>options.capabilities??voice,snapshot:()=>new Promise(()=>{}),input:async r=>{calls.push(['input',r]);activity=r.activity_seq;inputEpoch++;const effect={id:`speech-${activity}`,kind:'speech',value:'hello',digest:'a'.repeat(64),output_epoch:activity,activity_seq:activity};return session({phase:'ready',request_id:r.request_id,active_grants:[effect]});},stop:async r=>{calls.push(['network-stop',r]);activity=r.activity_seq;return session();},receipt:async r=>{received.push(r);return session();},audioProgress:async r=>{progress.push(r);return session();},speech:async (e,s,push)=>{calls.push(['speech',e]);await push(new Int16Array([1,2]));},microphone:(origin,signal,observers)=>{calls.push(['microphone',origin]);const d=deferred();const stream={ready:Promise.resolve(),completion:d.promise,send:c=>calls.push(['pcm',c]),finish:()=>{calls.push(['finish']);return d.promise;},cancel:()=>calls.push(['mic-cancel']),resolve:d.resolve,signal,observers};microphones.push(stream);return stream;},close:async()=>calls.push(['api-close'])};
 let playbackOptions,captureOptions;
 const sink={active:null,unlock:async()=>{calls.push(['unlock']);return true;},open:e=>{calls.push(['open',e]);sink.active=e;return {push:pcm=>{calls.push(['push',pcm]);playbackOptions.onFact({origin:e,stage:'submitted',submittedFrames:pcm.length,renderedFrames:0,sampleRate:24000,inFlightFramesUncertain:pcm.length});return true;},finish:()=>{calls.push(['sealed']);return true;}};},stop:reason=>{calls.push(['local-audio-stop',reason]);if(sink.active){const e=sink.active;sink.active=null;playbackOptions.onFact({origin:e,stage:'stopped',submittedFrames:2,renderedFrames:0,sampleRate:24000,inFlightFramesUncertain:2,reason});}},reconcileAuthorization:()=>{if(sink.active&&!playbackOptions.isAuthorized(sink.active))sink.stop('revoked');},close:async()=>{sink.stop('close');calls.push(['sink-close']);}};
 const capture={start:async()=>{calls.push(['capture-start']);captureOptions.onState('recording');return true;},stop:()=>{calls.push(['capture-stop']);captureOptions.onState('stopped');},close:async()=>calls.push(['capture-close'])};
 const effects={apply:e=>calls.push(['visual',e]),prepareInput:()=>calls.push(['prepare']),stop:()=>calls.push(['scene-stop']),setPhase:p=>phases.push(p)};
 const view={connected:()=>calls.push(['connected']),update:s=>calls.push(['view',s]),error:e=>errors.push(e),localStop:()=>calls.push(['view-stop']),capabilities:v=>calls.push(['capabilities',v]),microphone:s=>calls.push(['mic-state',s]),microphonePreview:value=>previews.push(value),microphoneTiming:value=>timings.push(value)};
 const controller=new SessionController(api,effects,view,{apiBase:'/api/v1',pollIntervalMs:200},{createPlayback:o=>{playbackOptions=o;return options.createPlayback?options.createPlayback(o):sink;},createCapture:o=>{captureOptions=o;return capture;},
  externalMicrophoneActive:options.externalMicrophoneActive,onGlobalStop:options.onGlobalStop});
 return {controller,api,sink,capture,calls,received,progress,errors,phases,microphones,previews,timings,session,get playback(){return playbackOptions;},get captureEvents(){return captureOptions;}};
}
test('new text stops locally before request and explicit speech never reaches DOM receipt',async()=>{const h=harness();await h.controller.connect();await h.controller.input('hello');await tick();assert.ok(h.calls.findIndex(x=>x[0]==='local-audio-stop')<h.calls.findIndex(x=>x[0]==='input'));assert.equal(h.calls.filter(x=>x[0]==='visual'&&x[1].kind==='speech').length,0);assert.equal(h.received.length,0);assert.equal(h.calls.filter(x=>x[0]==='speech').length,1);assert.equal(h.playback.isAuthorized(h.sink.active),true);await h.controller.close();});
test('stop terminal fact is sequenced within stop cutoff before network',async()=>{const h=harness();await h.controller.connect();await h.controller.input('hello');await tick();await h.controller.stop();await tick();const stop=h.calls.find(x=>x[0]==='network-stop')[1];assert.equal(h.progress.length,1);assert.equal(h.progress[0].status,'interrupted');assert.equal(stop.presentation_cutoff,h.progress[0].presentation_seq);assert.equal(h.sink.active,null);await h.controller.close();});
test('close during connect stays closed when create resolves late',async()=>{const h=harness(),pending=deferred();h.api.create=()=>pending.promise;const connect=h.controller.connect();await h.controller.close();pending.resolve({session:h.session(),session_token:'secret'});await connect;assert.equal(h.calls.some(x=>x[0]==='connected'),false);assert.ok(h.calls.some(x=>x[0]==='sink-close'));assert.ok(h.calls.some(x=>x[0]==='capture-close'));});
test('PTT stops sound, captures once, finishes and submits only final transcript',async()=>{const h=harness();await h.controller.connect();await h.controller.input('hello');await tick();await h.controller.startMicrophone();await tick();assert.equal(h.calls.filter(x=>x[0]==='capture-start').length,1);const lastStop=h.calls.findLastIndex(x=>x[0]==='local-audio-stop');assert.ok(lastStop<h.calls.findIndex(x=>x[0]==='capture-start'));assert.ok(h.phases.includes('listening'));const end=h.controller.finishMicrophone();await tick();h.microphones[0].resolve({text:'new reliable words',had_final:true});await end;await tick();assert.equal(h.calls.filter(x=>x[0]==='input').length,2);await h.controller.close();});
test('stop during pending final transcript prevents late new causal input',async()=>{const h=harness();await h.controller.connect();await h.controller.startMicrophone();await tick();const finish=h.controller.finishMicrophone();await tick();await h.controller.stop();h.microphones[0].resolve({text:'too late',had_final:true});await finish;assert.equal(h.calls.filter(x=>x[0]==='input').length,0);await h.controller.close();});
test('empty, interim-only and noise transcripts do not create input',async()=>{for(const result of [{text:'',had_final:true},{text:'interim',had_final:false},{text:'[noise]',had_final:true}]){const h=harness();await h.controller.connect();await h.controller.startMicrophone();await tick();const finish=h.controller.finishMicrophone();await tick();h.microphones[0].resolve(result);await finish;assert.equal(h.calls.filter(x=>x[0]==='input').length,0);await h.controller.close();}});

test('late failure from an old fact outside the captured cutoff cannot stop newer input playback',async()=>{const h=harness(),late=deferred();await h.controller.connect();await h.controller.input('first');await tick();await h.controller.input('second');await tick();const second=h.sink.active;const request=h.calls.filter(x=>x[0]==='input').at(-1)[1];const outsideSequence=request.presentation_cutoff+1;h.api.audioProgress=async fact=>{if(fact.presentation_seq===outsideSequence)await late.promise;return h.session();};h.controller.enqueueFact({effect_id:'speech-1',digest:'a'.repeat(64),output_epoch:1,activity_seq:1,presentation_seq:outsideSequence,sample_rate_hz:24000,rendered_samples:0,status:'interrupted'},true,1);await tick();late.reject(new Error('stale old history transport failed'));await tick();assert.equal(h.sink.active,second);assert.ok(h.errors.some(x=>x.includes('History may be incomplete')));await h.controller.close();});
test('uncooperative older input result cannot revive stop',async()=>{const h=harness(),oldInput=deferred();h.api.input=()=>oldInput.promise;await h.controller.connect();const input=h.controller.input('first');await h.controller.stop();oldInput.resolve(h.session({phase:'ready',activity_seq:1,output_epoch:1,request_id:'old',active_grants:[{id:'late',kind:'speech',value:'no',digest:'a'.repeat(64),output_epoch:1,activity_seq:1}]}));await input;assert.equal(h.sink.active,null);assert.equal(h.calls.filter(x=>x[0]==='speech').length,0);await h.controller.close();});
test('current malformed or foreign snapshot fails closed before applying audio',async()=>{const h=harness();await h.controller.connect();await h.controller.input('hello');await tick();h.controller.install(h.session({session_id:'foreign',phase:'ready'}));assert.equal(h.sink.active,null);assert.ok(h.errors.length);await h.controller.close();});
function realSinkHarness(){const sources=[],timers=new Set();const context={destination:{},resume:async()=>{},close:async()=>{},createBuffer:(_channels,length)=>({getChannelData:()=>new Float32Array(length)}),createBufferSource:()=>{const source={onended:null,stopped:0,connect(){},disconnect(){},start(){},stop(){this.stopped++;}};sources.push(source);return source;}};const h=harness({createPlayback:options=>new CancelSafePlayback({...options,createContext:()=>context,setInterval:fn=>{timers.add(fn);return fn;},clearInterval:id=>timers.delete(id)})});return {...h,sources,timers};}
test('real single sink backpressures long speech to four seconds and stop releases blocked packet',async()=>{const h=realSinkHarness();let accepted=0;h.api.speech=async(_e,_signal,push)=>{for(let i=0;i<30;i++){await push(new Int16Array(6000));accepted++;}};await h.controller.connect();await h.controller.input('long speech');await tick();assert.equal(accepted,16);assert.equal(h.sources.length,1);const oldEnd=h.sources[0].onended;h.sources[0].onended();await tick();assert.equal(accepted,17);await h.controller.stop();oldEnd();await tick();assert.equal(accepted,17);assert.equal(h.sources.length,2);assert.equal(h.progress.at(-1).status,'interrupted');assert.equal(h.progress.at(-1).rendered_samples,6000);await h.controller.close();assert.equal(h.timers.size,0);});
test('real long speech completes only after every naturally ended source',async()=>{const h=realSinkHarness();h.api.speech=async(_e,_signal,push)=>{for(let i=0;i<30;i++)await push(new Int16Array(6000));};await h.controller.connect();await h.controller.input('long speech');await tick();for(let i=0;i<30;i++){assert.equal(h.progress.some(x=>x.status==='completed'),false);assert.ok(h.sources[i]);h.sources[i].onended();await tick();}assert.equal(h.progress.at(-1).status,'completed');assert.equal(h.progress.at(-1).rendered_samples,180000);assert.equal(h.received.length,0);assert.equal(h.phases.at(-1),'idle');await h.controller.close();});
test('ready and idle snapshots preserve actual speaking until its source ends',async()=>{const h=realSinkHarness();await h.controller.connect();await h.controller.input('hello');await tick();const current=h.controller.snapshot;h.controller.install({...current,revision:current.revision+1,phase:'idle'});assert.equal(h.phases.at(-1),'speaking');h.sources[0].onended();await tick();assert.equal(h.phases.at(-1),'idle');await h.controller.close();});
test('revoked grants stop active source and saved source callbacks cannot restart it',async()=>{const h=realSinkHarness();await h.controller.connect();await h.controller.input('hello');await tick();const oldEnd=h.sources[0].onended,current=h.controller.snapshot;h.controller.install({...current,revision:current.revision+1,permit_revision:current.permit_revision+1,active_grants:[]});assert.equal(h.sources[0].stopped,1);oldEnd();await tick();assert.equal(h.progress.at(-1).status,'interrupted');assert.equal(h.progress.some(x=>x.status==='completed'),false);await h.controller.close();});
test('late speech packets and explicit stream completion cannot restart after stop',async()=>{const h=harness(),done=deferred();let push;h.api.speech=async(_e,_signal,onPcm)=>{push=onPcm;await onPcm(new Int16Array([1,2]));await done.promise;};await h.controller.connect();await h.controller.input('hello');await tick();await h.controller.stop();await assert.rejects(push(new Int16Array([3,4])));done.resolve();await tick();assert.equal(h.sink.active,null);assert.equal(h.calls.some(x=>x[0]==='sealed'),false);await h.controller.close();});
test('late capture readiness after new text cannot change its speaking phase',async()=>{const h=harness(),permission=deferred();h.capture.start=()=>permission.promise;await h.controller.connect();const start=h.controller.startMicrophone();await tick();await h.controller.input('new words');await tick();h.captureEvents.onState('recording');permission.resolve(false);await start;assert.equal(h.phases.at(-1),'speaking');assert.ok(h.sink.active);await h.controller.close();});
test('PTT released before stop acknowledgement queues bounded PCM then drains before finish',async()=>{const h=harness(),stopped=deferred();h.api.stop=r=>{h.calls.push(['network-stop',r]);return stopped.promise;};await h.controller.connect();await h.controller.startMicrophone();h.captureEvents.onChunk({pcm16le:new Uint8Array([1,0,2,0]),sampleRate:16000,channels:1,sequence:0,startSample:0,endSample:2,captureSampleRate:48000,sourceSampleRate:null,captureStartFrame:0});const finish=h.controller.finishMicrophone();assert.equal(h.microphones.length,0);stopped.resolve(h.session({activity_seq:1,output_epoch:1,input_epoch:0}));await tick();assert.equal(h.microphones.length,1);assert.ok(h.calls.findIndex(x=>x[0]==='pcm')<h.calls.findIndex(x=>x[0]==='finish'));h.microphones[0].resolve({text:'',had_final:false});await finish;assert.equal(h.calls.filter(x=>x[0]==='input').length,0);await h.controller.close();});
test('software rendered facts precede terminal delivery while Stop is immediately local',async()=>{const h=realSinkHarness(),first=deferred(),delivered=[];h.api.audioProgress=async fact=>{delivered.push(fact);if(delivered.length===1)await first.promise;return h.session();};h.api.speech=async(_e,_signal,push)=>{await push(new Int16Array(2));await push(new Int16Array(2));};await h.controller.connect();await h.controller.input('hello');await tick();h.sources[0].onended();await tick();await h.controller.stop();assert.equal(h.sources[1].stopped,1);assert.deepEqual(delivered.map(x=>x.status),['rendered']);const cutoff=h.calls.find(x=>x[0]==='network-stop')[1].presentation_cutoff;first.resolve();await tick();assert.deepEqual(delivered.map(x=>x.status),['rendered','interrupted']);assert.equal(delivered[1].presentation_seq,cutoff);await h.controller.close();});

const rehearsalVoice={...voice,microphone_enabled:false,generation_mode:'rehearsal',qualification:'offline_fixture'};
test('offline synthetic listening never opens microphone and releases one fixed command',async()=>{const h=harness({capabilities:rehearsalVoice});await h.controller.connect();await tick();await h.controller.startRehearsalInput();assert.equal(h.phases.at(-1),'listening');assert.equal(h.calls.some(x=>x[0]==='capture-start'||x[0]==='microphone'),false);await h.controller.finishRehearsalInput();await h.controller.finishRehearsalInput();await tick();const inputs=h.calls.filter(x=>x[0]==='input');assert.equal(inputs.length,1);assert.equal(inputs[0][1].text,'照片里有什么');assert.equal(h.phases.at(-1),'speaking');await h.controller.close();});
test('synthetic input release before stop acknowledgement waits and Stop prevents late submission',async()=>{const h=harness({capabilities:rehearsalVoice}),ack=deferred();h.api.stop=r=>ack.promise;await h.controller.connect();await tick();const start=h.controller.startRehearsalInput();const finish=h.controller.finishRehearsalInput();assert.equal(h.calls.some(x=>x[0]==='input'),false);const stopped=h.controller.stop();ack.resolve(h.session({activity_seq:2,output_epoch:2}));await Promise.all([start,finish,stopped]);assert.equal(h.calls.some(x=>x[0]==='input'),false);await h.controller.close();});
test('new text and close each invalidate held synthetic input',async()=>{for(const action of ['text','close']){const h=harness({capabilities:rehearsalVoice});await h.controller.connect();await tick();await h.controller.startRehearsalInput();if(action==='text')await h.controller.input('你好');else await h.controller.close();await h.controller.finishRehearsalInput();assert.deepEqual(h.calls.filter(x=>x[0]==='input').map(x=>x[1].text),action==='text'?['你好']:[]);await h.controller.close();}});
test('synthetic listening is unavailable outside explicit rehearsal capability',async()=>{const h=harness();await h.controller.connect();await tick();await h.controller.startRehearsalInput();await h.controller.finishRehearsalInput();assert.equal(h.calls.some(x=>x[0]==='network-stop'||x[0]==='input'||x[0]==='capture-start'),false);await h.controller.close();});


test('microphone revisions remain provisional and finish, newer input, permission denial, Stop and Close clear stale callbacks',async()=>{
 const h=harness();
 try {
  await h.controller.connect();await h.controller.startMicrophone();await tick();
  const stream=h.microphones[0],id=h.calls.find(x=>x[0]==='microphone')[1].stream_id;
  stream.observers.onRevision({stream_id:id,revision:1,text:'provisional only',is_final:false});
  assert.equal(h.previews.at(-1).text,'provisional only');
  const finish=h.controller.finishMicrophone();await tick();assert.equal(h.previews.at(-1),null);
  stream.resolve({text:'reliable final only',had_final:true});await finish;await tick();
  assert.equal(h.calls.filter(x=>x[0]==='input').at(-1)[1].text,'reliable final only');assert.equal(h.previews.at(-1),null);

  await h.controller.startMicrophone();await tick();const newer=h.microphones.at(-1),newId=h.calls.findLast(x=>x[0]==='microphone')[1].stream_id;
  newer.observers.onRevision({stream_id:newId,revision:1,text:'clear on newer text',is_final:false});
  await h.controller.input('newer user text');assert.equal(h.previews.at(-1),null);
  newer.observers.onRevision({stream_id:newId,revision:2,text:'old generation',is_final:false});assert.equal(h.previews.at(-1),null);

  await h.controller.startMicrophone();await tick();const denied=h.microphones.at(-1),deniedId=h.calls.findLast(x=>x[0]==='microphone')[1].stream_id;
  denied.observers.onRevision({stream_id:deniedId,revision:1,text:'clear on permission denial',is_final:false});
  h.captureEvents.onError(new Error('synthetic permission denial'));assert.equal(h.previews.at(-1),null);
  denied.observers.onRevision({stream_id:deniedId,revision:2,text:'stale after denial',is_final:false});assert.equal(h.previews.at(-1),null);

  await h.controller.startMicrophone();await tick();const stopped=h.microphones.at(-1),stopId=h.calls.findLast(x=>x[0]==='microphone')[1].stream_id;
  stopped.observers.onRevision({stream_id:stopId,revision:1,text:'clear on stop',is_final:false});
  await h.controller.stop();assert.equal(h.previews.at(-1),null);
  stopped.observers.onRevision({stream_id:stopId,revision:2,text:'old after stop',is_final:false});assert.equal(h.previews.at(-1),null);

  await h.controller.startMicrophone();await tick();const closed=h.microphones.at(-1),closeId=h.calls.findLast(x=>x[0]==='microphone')[1].stream_id;
  closed.observers.onRevision({stream_id:closeId,revision:1,text:'clear on close',is_final:false});
  await h.controller.close();assert.equal(h.previews.at(-1),null);
  closed.observers.onRevision({stream_id:closeId,revision:2,text:'old after close',is_final:false});assert.equal(h.previews.at(-1),null);
 } finally {await h.controller.close();}
});

test('manual continuous transcript uses the ordinary receipt-prefix input request and survives reply-turn generation changes',async()=>{
 const stopReasons=[];let continuousActive=true;
 const h=harness({externalMicrophoneActive:()=>continuousActive,onGlobalStop:reason=>{stopReasons.push(reason);}});
 try {
  await h.controller.connect();
  assert.equal(h.controller.canAuditionReviewedAudio(),false,'raw-audio audition is blocked during continuous capture');
  const outcome=await h.controller.input('server-confirmed phrase',undefined,'22345678-1234-4234-8234-123456789012');
  assert.equal(outcome.status,'submitted');
  const request=h.calls.filter(call=>call[0]==='input').at(-1)[1];
  assert.equal(request.text,'server-confirmed phrase');
  assert.equal(request.listening_utterance_id,'22345678-1234-4234-8234-123456789012');
  assert.equal(Number.isInteger(request.activity_seq),true);assert.equal(Number.isInteger(request.presentation_cutoff),true);
  assert.equal(continuousActive,true,'ordinary reply/input epoch changes do not own the separate mic lease');
  assert.deepEqual(stopReasons,[],'normal new-input interruption must not invoke the global mic release');
  continuousActive=false;await h.controller.stop();assert.deepEqual(stopReasons,['stop']);
  await h.controller.close();assert.deepEqual(stopReasons,['stop','close']);
 } finally {await h.controller.close();}
});
