import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import vm from 'node:vm';
const dist=process.env.MIRA_TEST_WEB_DIST?resolve(process.env.MIRA_TEST_WEB_DIST):resolve('apps/web/dist');
const source=(await readFile(resolve(dist,'app/main.js'),'utf8')).replace(/^import .*;\n/gm,'');
function app(){const calls=[];const nodes=new Map();class Node {listeners={};disabled=false;dataset={};value='';textContent='';addEventListener(name,fn){(this.listeners[name]??=[]).push(fn);}fire(name,patch={}){const e={preventDefault(){},button:0,pointerId:1,...patch};for(const fn of this.listeners[name]??[])fn(e);}setAttribute(name,value){this[name]=value;}setPointerCapture(){}releasePointerCapture(){}hasPointerCapture(){return true;}}
for(const selector of ['[data-status]','[data-diagnostic]','[data-error]','[data-stage]','fieldset','form','[name=message]','[data-stop]','[data-close]','[data-ptt]','[data-voice-hint]','[data-mode-label]','[data-mode-description]','[data-recording-notice]','[data-rehearsal-banner]','[data-rehearsal-controls]','[data-rehearsal-input]','[data-rehearsal-hint]'])nodes.set(selector,new Node());
const window=new Node();const document={querySelector:s=>nodes.get(s),querySelectorAll:()=>[],visibilityState:'visible',addEventListener:()=>{}};let view;
class SessionController {constructor(_api,_effects,v){view=v;}connect(){calls.push('connect');return Promise.resolve();}input(){calls.push('input');return Promise.resolve();}stop(){calls.push('stop');return Promise.resolve();}close(){calls.push('close');return Promise.resolve();}startMicrophone(){calls.push('start');return Promise.resolve();}finishMicrophone(){calls.push('finish');return Promise.resolve();}startRehearsalInput(){calls.push('rehearsal-start');return Promise.resolve();}finishRehearsalInput(){calls.push('rehearsal-finish');return Promise.resolve();}}
vm.runInNewContext(source,{document,window,globalThis:{AudioContext:class{},AudioWorkletNode:class{},isSecureContext:true},navigator:{mediaDevices:{getUserMedia(){}}},isSecureContext:true,loadPublicConfig:()=>({}),watchDiagnosticsStatus:()=>({close(){}}),recordingNotice:()=>({visible:false,text:"",state:"off"}),safeSessionError:()=>"safe error",MiraApiClient:class{},SessionController,DomEffectExecutor:class{constructor(){calls.push('dom');}},SceneEffectExecutor:class{constructor(){calls.push('scene');}}});
return {nodes,calls,view,window};}
test('composition selects scene executor and labels actual backend capability',()=>{const h=app();assert.equal(h.calls.includes('scene'),true);assert.equal(h.calls.includes('dom'),false);h.view.capabilities({generation_mode:'replay',speech_enabled:false,microphone_enabled:false,qualification:'unavailable'});assert.match(h.nodes.get('[data-mode-label]').textContent,/Fixture/);assert.equal(h.nodes.get('[data-ptt]').disabled,true);});
test('PTT pointer and keyboard gestures start once and release once, cancellation stops',()=>{const h=app(),ptt=h.nodes.get('[data-ptt]');h.view.capabilities({generation_mode:'injected',speech_enabled:true,microphone_enabled:true,qualification:'injected_unverified'});ptt.fire('pointerdown');ptt.fire('pointerdown');ptt.fire('pointerup');assert.deepEqual(h.calls.filter(x=>['start','finish'].includes(x)),['start','finish']);ptt.fire('keydown',{key:' ',repeat:false});ptt.fire('keydown',{key:' ',repeat:true});ptt.fire('keyup',{key:' '});assert.equal(h.calls.filter(x=>x==='start').length,2);assert.equal(h.calls.filter(x=>x==='finish').length,2);ptt.fire('pointerdown');ptt.fire('pointercancel');assert.equal(h.calls.at(-1),'stop');});
test('empty text submission cannot orphan a held microphone gesture',()=>{const h=app(),ptt=h.nodes.get('[data-ptt]');h.view.capabilities({generation_mode:'injected',speech_enabled:true,microphone_enabled:true,qualification:'injected_unverified'});ptt.fire('pointerdown');h.nodes.get('[name=message]').value='   ';h.nodes.get('form').fire('submit');ptt.fire('pointerup');assert.equal(h.calls.filter(x=>x==='input').length,0);assert.equal(h.calls.filter(x=>x==='finish').length,1);});

test('explicit rehearsal shows honest banner, microphone off and synthetic hold input controls',()=>{const h=app();h.view.capabilities({generation_mode:'rehearsal',speech_enabled:true,microphone_enabled:false,qualification:'offline_fixture'});assert.equal(h.nodes.get('[data-rehearsal-banner]').hidden,false);assert.match(h.nodes.get('[data-mode-description]').textContent,/英文.*合成/);assert.equal(h.nodes.get('[data-ptt]').disabled,true);const button=h.nodes.get('[data-rehearsal-input]');button.fire('pointerdown');button.fire('pointerdown');button.fire('pointerup');assert.deepEqual(h.calls.filter(x=>x.startsWith('rehearsal')),['rehearsal-start','rehearsal-finish']);assert.equal(h.calls.includes('start'),false);button.fire('keydown',{key:' ',repeat:false});button.fire('keyup',{key:' '});assert.equal(h.calls.filter(x=>x==='rehearsal-finish').length,2);button.fire('pointerdown');h.window.fire('blur');assert.equal(h.calls.at(-1),'stop');button.fire('pointerup');assert.equal(h.calls.filter(x=>x==='rehearsal-finish').length,2);});
