import test from 'node:test';
import assert from 'node:assert/strict';
import {resolve} from 'node:path';
import {readFileSync} from 'node:fs';
import {pathToFileURL} from 'node:url';
const dist=process.env.MIRA_TEST_WEB_DIST?pathToFileURL(resolve(process.env.MIRA_TEST_WEB_DIST)+'/').href:new URL('../../apps/web/dist/',import.meta.url).href;
const {safeSessionError}=await import(new URL('features/diagnostics/status.js',dist));
const {parseSession}=await import(new URL('shared/protocol.js',dist));
const {BrowserAudioTransport}=await import(new URL('features/session/audio-transport.js',dist));
const backendFixture=process.env.MIRA_ERROR_FIXTURE?JSON.parse(readFileSync(process.env.MIRA_ERROR_FIXTURE,'utf8')):null;
const id=backendFixture?.session.last_error_diagnostic_id??'h_'+'a'.repeat(32),privateMarker='SYNTHETIC_PRIVATE_BODY';
const tick=()=>new Promise(r=>setImmediate(r));
const base={schema_version:'0.1.0-foundation',session_id:'s',client_instance_id:'c',revision:1,activity_seq:0,input_epoch:0,output_epoch:0,permit_revision:1,phase:'stopped',request_id:null,sealed:true,active_grants:[],presented_effects:[],audio_progress:[],last_error:null};
const effect={id:'e',kind:'speech',value:'approved synthetic',digest:'a'.repeat(64),output_epoch:1,activity_seq:1};
const origin={effect_id:'e',stream_id:'e',digest:effect.digest,output_epoch:1,activity_seq:1};
function transport(fetcher,createSocket){return new BrowserAudioTransport({apiBase:'/api/v1',pollIntervalMs:200},()=>({sessionId:'s',token:'synthetic-capability'}),{fetch:fetcher,createSocket,baseUrl:'https://mira.test/'});}
class Socket {readyState=1;bufferedAmount=0;send(){}close(){}message(value){this.onmessage?.({data:JSON.stringify(value)})}}
for(const bad of ['constructor','toString','__proto__',privateMarker,'h_'+'a'.repeat(32)+'\n',{toString:()=>id},123])test(`untrusted locator ${typeof bad==='string'?JSON.stringify(bad):typeof bad} is discarded`,()=>{const parsed=parseSession({...base,phase:'error',last_error:'constructor',last_error_diagnostic_id:bad});assert.equal(parsed.last_error_diagnostic_id,null);const message=safeSessionError('constructor',bad);assert.match(message,/重试/);assert.equal(message.includes('诊断编号'),false);assert.equal(message.includes(privateMarker),false)});
test('prototype inherited locator is not a DTO field',()=>{const input=Object.assign(Object.create({last_error_diagnostic_id:id}),base,{last_error:'generation_timeout',phase:'error'});assert.equal(parseSession(input).last_error_diagnostic_id,null)});
test('validated locator remains safe and immutable for known or unknown errors',()=>{for(const code of ['generation_timeout','constructor',privateMarker]){const raw={...base,phase:'error',last_error:code,last_error_diagnostic_id:id};const parsed=parseSession(raw);raw.last_error_diagnostic_id='h_'+'b'.repeat(32);assert.equal(parsed.last_error_diagnostic_id,id);assert.ok(safeSessionError(code,parsed.last_error_diagnostic_id).includes(id));assert.equal(safeSessionError(code,id).includes(privateMarker),false)}});
for(const code of ['timeout','constructor',privateMarker])test(`NDJSON error preserves locator and safe Chinese copy: ${code}`,async()=>{const api=transport(async()=>new Response(JSON.stringify({...origin,type:'error',code,diagnostic_id:id})+'\n',{headers:{'content-type':'application/x-ndjson'}}));await assert.rejects(api.speech(effect,new AbortController().signal,()=>{}),e=>e.message.includes(id)&&/重试|文字/.test(e.message)&&!e.message.includes(privateMarker));api.close()});
test('speech HTTP failure preserves validated request header',async()=>{const request='12345678-1234-1234-1234-123456789abc',api=transport(async()=>new Response(privateMarker,{status:503,headers:{'x-request-id':request}}));await assert.rejects(api.speech(effect,new AbortController().signal,()=>{}),e=>e.message.includes(request)&&/文字/.test(e.message)&&!e.message.includes(privateMarker));api.close()});
test('microphone typed failure survives validation catch with same locator',async()=>{const socket=new Socket(),api=transport(undefined,()=>socket),mic=api.microphone({stream_id:'m',activity_seq:1,input_epoch:1},new AbortController().signal);socket.onopen();socket.message({type:'error',code:'timeout',diagnostic_id:id});await assert.rejects(mic.ready,e=>e.message.includes(id)&&/重试|文字/.test(e.message));await assert.rejects(mic.completion,e=>e.message.includes(id));api.close()});
for(const kind of ['speech','microphone'])test(`${kind} invalid locator and provider text never reflected`,async()=>{let promise,api;if(kind==='speech'){api=transport(async()=>new Response(JSON.stringify({...origin,type:'error',code:privateMarker,diagnostic_id:privateMarker})+'\n',{headers:{'content-type':'application/x-ndjson'}}));promise=api.speech(effect,new AbortController().signal,()=>{});}else{const socket=new Socket();api=transport(undefined,()=>socket);const mic=api.microphone({stream_id:'m',activity_seq:1,input_epoch:1},new AbortController().signal);promise=mic.ready;socket.message({type:'error',code:privateMarker,diagnostic_id:privateMarker})}await assert.rejects(promise,e=>!e.message.includes(privateMarker)&&/重试|文字/.test(e.message));api.close()});
let sequence=0;
async function app(){
 const globals={window:globalThis.window,document:globalThis.document,fetch:globalThis.fetch,AudioContext:globalThis.AudioContext},nodes=new Map();
 class Node{listeners={};dataset={};value='';disabled=false;hidden=true;textContent='';addEventListener(n,f){(this.listeners[n]??=[]).push(f)}setAttribute(n,v){this[n]=v}querySelector(s){return nodes.get(s)}fire(n){for(const f of this.listeners[n]??[])f({preventDefault(){},button:0,pointerId:1})}setPointerCapture(){}}
 for(const s of ['[data-status]','[data-diagnostic]','[data-error]','[data-stage]','fieldset','form','[name=message]','[data-stop]','[data-close]','[data-ptt]','[data-voice-hint]','[data-mode-label]','[data-mode-description]','[data-recording-notice]','[data-review-audio-notice]','[data-review-audio-status]','[data-review-audio-scope]','[data-review-audio-eligibility]','[data-review-audio-consent]','[data-review-audio-enable]','[data-review-audio-disable]','[data-review-audio-review]','[data-review-audio-clip]','[data-review-audio-clip-metadata]','[data-review-audio-preview]','[data-review-audio-audition]','[data-review-audio-audition-status]','[data-review-audio-attestation]','[data-review-audio-confirm]','[data-review-audio-cancel]','[data-review-audio-result]','[data-rehearsal-banner]','[data-rehearsal-controls]','[data-rehearsal-input]','[data-rehearsal-hint]','[data-subtitle]','[data-photo]','[data-pose]','[data-scene-label]','[data-phase-label]','[data-character-description]'])nodes.set(s,new Node());
 globalThis.window=new Node();globalThis.document={querySelector:s=>nodes.get(s),querySelectorAll:()=>[],addEventListener(){},visibilityState:'visible'};globalThis.AudioContext=class{async resume(){}async close(){}};
 let client,revision=0,inputCount=0;const snapshot=patch=>({...base,client_instance_id:client,revision:++revision,permit_revision:revision,...patch});
 globalThis.fetch=async(url,options)=>{const path=String(url);if(path.endsWith('/diagnostics-status'))return Response.json({available:true,recording_active:false,notice:'',dropped_events:0,dropped_recordings:0,io_failures:0,pending_records:0});if(path.endsWith('/reviewed-audio')&&options.method==='GET')return Response.json({scope:'application',recording_active:false,has_pending_audio:false,staged_bytes:0,max_audio_bytes:512*1024,expires_in_seconds:0,pending_stream_id:null,pending_kind:null,input_completion_ready:false,notice:'off',scope_notice:'all local sessions'});if(path.endsWith('/voice-capabilities'))return Response.json({speech_enabled:false,microphone_enabled:false,speech_sample_rate_hz:24000,microphone_sample_rate_hz:16000,generation_mode:'mock',qualification:'unavailable'});if(path.endsWith('/sessions')&&options.method==='POST'){client=JSON.parse(options.body).client_instance_id;return Response.json({session:snapshot({}),session_token:'synthetic-token'})}if(path.endsWith('/inputs')){const request=JSON.parse(options.body);inputCount++;return Response.json(snapshot({activity_seq:request.activity_seq,input_epoch:inputCount,output_epoch:request.activity_seq,phase:inputCount===1?'error':'thinking',request_id:inputCount===1?null:request.request_id,last_error:inputCount===1?(backendFixture?.session.last_error??'generation_timeout'):null,last_error_diagnostic_id:inputCount===1?id:null}))}if(path.endsWith('/stop')||options.method==='GET')return await new Promise((resolve,reject)=>{options.signal.addEventListener('abort',()=>reject(new Error('synthetic abort')),{once:true})});if(options.method==='DELETE')return new Response(null,{status:204});throw new Error('Unexpected synthetic fetch')};
 await import(new URL(`app/main.js?locator=${++sequence}`,dist));await tick();return{nodes,async submit(){nodes.get('[name=message]').value='Synthetic input';nodes.get('form').fire('submit');await tick();await tick()},async close(){nodes.get('[data-close]').fire('click');await tick();await tick();for(const[key,value]of Object.entries(globals)){if(value===undefined)delete globalThis[key];else globalThis[key]=value}}};
}
for(const action of ['stop','new-input'])test(`actual main API/controller DOM keeps async locator and clears immediately on ${action}`,async()=>{const h=await app();try{await h.submit();assert.ok(h.nodes.get('[data-error]').textContent.includes(id));assert.match(h.nodes.get('[data-error]').textContent,/重试/);if(action==='stop')h.nodes.get('[data-stop]').fire('click');else await h.submit();assert.equal(h.nodes.get('[data-error]').textContent,'')}finally{await h.close()}});

test('late old snapshot or history-delivery failure cannot replace new-turn locator',async()=>{
 const {SessionController}=await import(new URL('features/session/controller.js',dist));
 let client,revision=0,rejectOld;const errors=[];
 const snap=patch=>({...base,client_instance_id:client,revision:++revision,permit_revision:revision,...patch});
 const api={create:async c=>{client=c;return{session:snap({}),session_token:'synthetic'}},capabilities:async()=>({speech_enabled:false,microphone_enabled:false}),snapshot:()=>new Promise(()=>{}),receipt:()=>new Promise((_,reject)=>{rejectOld=reject}),input:async r=>snap({phase:'error',activity_seq:r.activity_seq,input_epoch:1,output_epoch:1,last_error:'generation_timeout',last_error_diagnostic_id:id}),close:async()=>{}};
 const controller=new SessionController(api,{prepareInput(){},stop(){},apply(){}},{connected(){},update(){},error:e=>errors.push(e),localStop(){}},{apiBase:'/api/v1',pollIntervalMs:200},{createPlayback:()=>({unlock:async()=>true,stop(){},close:async()=>{},reconcileAuthorization(){}}),createCapture:()=>({start:async()=>false,stop(){},close:async()=>{}})});
 try{await controller.connect();controller.enqueueFact({},false);await tick();await controller.input('new synthetic input');assert.ok(errors.at(-1).includes(id));rejectOld(new Error(privateMarker));await tick();controller.install(snap({activity_seq:0,phase:'error',last_error:'timeout',last_error_diagnostic_id:'h_'+'b'.repeat(32)}));assert.ok(errors.at(-1).includes(id));assert.equal(errors.some(e=>e.includes(privateMarker)),false)}finally{await controller.close()}
});
