import test from 'node:test';
import assert from 'node:assert/strict';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
const dist=process.env.MIRA_TEST_WEB_DIST?pathToFileURL(resolve(process.env.MIRA_TEST_WEB_DIST)+'/').href:new URL('../../apps/web/dist/',import.meta.url).href;
const {BrowserAudioTransport}=await import(new URL('features/session/audio-transport.js',dist));
const origin={id:'effect-1',kind:'speech',value:'secret original text',digest:'a'.repeat(64),output_epoch:1,activity_seq:1};
const packet={effect_id:origin.id,digest:origin.digest,output_epoch:1,activity_seq:1,stream_id:origin.id};
const signal=()=>new AbortController().signal;
function response(items){const text=items.map(x=>JSON.stringify(x)+'\n').join('');return new Response(text,{headers:{'Content-Type':'application/x-ndjson'}});}
const audio=(changes={})=>({...packet,type:'audio',sequence:1,first_sample:0,sample_rate_hz:24000,pcm_base64:Buffer.from([0,128,255,127]).toString('base64'),...changes});
const complete=(changes={})=>({...packet,type:'complete',total_samples:2,...changes});
function transport(fetcher, socket, extra={}){return new BrowserAudioTransport({apiBase:'/api/v1',pollIntervalMs:200},()=>({sessionId:'session-1',token:'capability-secret'}),{fetch:fetcher,createSocket:socket,baseUrl:'https://mira.test/',...extra});}
test('speech validates PCM, origin and terminal while keeping token out of URL/body',async()=>{let request;const got=[];const api=transport(async(url,options)=>{request={url,options};return response([audio(),complete()]);});await api.speech(origin,signal(),pcm=>got.push([...pcm]));assert.deepEqual(got,[[-32768,32767]]);assert.match(request.url,/\/speech\/effect-1\/stream$/);assert.equal(request.url.includes('capability-secret'),false);assert.equal(request.options.headers['X-Mira-Session-Token'],'capability-secret');assert.deepEqual(JSON.parse(request.options.body),{digest:origin.digest,output_epoch:1,activity_seq:1});});
test('speech rejects truncation, sequence holes, foreign origin and invalid formats',async()=>{for(const items of [[audio()],[audio({sequence:2}),complete()],[audio({digest:'b'.repeat(64)}),complete()],[audio({sample_rate_hz:16000}),complete()],[audio({pcm_base64:'AA=='}),complete()],[audio(),complete({total_samples:3})]]) {const api=transport(async()=>response(items));await assert.rejects(api.speech(origin,signal(),()=>{}));}});
class Socket {readyState=0;bufferedAmount=0;onopen=null;onmessage=null;onerror=null;onclose=null;sent=[];closed=false;send(text){this.sent.push(JSON.parse(text));}close(){this.closed=true;this.readyState=3;}open(){this.readyState=1;this.onopen?.({});}message(value){this.onmessage?.({data:JSON.stringify(value)});}}
const micOrigin={stream_id:'12345678-1234-4234-8234-123456789012',activity_seq:2,input_epoch:1};
function chunk(seq=0){return {pcm16le:new Uint8Array([1,0,2,0]),sampleRate:16000,channels:1,sequence:seq,startSample:seq*2,endSample:seq*2+2,captureSampleRate:48000,sourceSampleRate:null,captureStartFrame:seq*6};}
test('microphone authenticates first message and drains PCM before explicit finish',async()=>{const socket=new Socket();let url;const api=transport(undefined,u=>{url=u;return socket;});const mic=api.microphone(micOrigin,signal());mic.send(chunk());socket.open();assert.equal(url,'wss://mira.test/api/v1/sessions/session-1/microphone');assert.equal(socket.sent[0].type,'start');assert.equal(socket.sent[0].session_token,'capability-secret');socket.message({type:'ready',...micOrigin});await mic.ready;const done=mic.finish();assert.deepEqual(socket.sent.map(x=>x.type),['start','audio','finish']);socket.message({type:'transcript',stream_id:micOrigin.stream_id,revision:1,text:'unreliable interim',is_final:false});socket.message({type:'complete',stream_id:micOrigin.stream_id,revision:2,text:'reliable final',had_final:true});assert.deepEqual(await done,{text:'reliable final',had_final:true});assert.equal(socket.closed,true);});
test('microphone cancel suppresses late ready, transcript and completion',async()=>{const socket=new Socket();const api=transport(undefined,()=>socket);const abort=new AbortController();const mic=api.microphone(micOrigin,abort.signal);const rejected=assert.rejects(mic.ready);abort.abort();socket.open();socket.message({type:'ready',...micOrigin});await rejected;assert.equal(socket.sent.length,0);assert.throws(()=>mic.send(chunk()));assert.equal(socket.closed,true);});
test('microphone rejects bounded queue overflow before authentication',()=>{const socket=new Socket();const api=transport(undefined,()=>socket);const mic=api.microphone(micOrigin,signal());assert.throws(()=>{for(let i=0;i<10000;i++)mic.send(chunk(i));});assert.equal(socket.closed,true);api.close();});
test('malformed speech JSON never reflects raw server content in the surfaced error',async()=>{const api=transport(async()=>new Response('SECRET\n',{headers:{'content-type':'application/x-ndjson'}}));await assert.rejects(api.speech(origin,signal(),()=>{}),error=>!error.message.includes('SECRET'));});
test('microphone drains bounded browser buffer before finish without timer races',async()=>{const socket=new Socket(),timers=new Map();let id=0;const api=transport(undefined,()=>socket,{setTimeout:(fn,ms)=>{timers.set(++id,{fn,ms});return id;},clearTimeout:id=>timers.delete(id)});const mic=api.microphone(micOrigin,signal());socket.open();socket.message({type:'ready',...micOrigin});await mic.ready;socket.bufferedAmount=65536;mic.send(chunk());const final=mic.finish();assert.deepEqual(socket.sent.map(x=>x.type),['start']);socket.bufferedAmount=0;[...timers.values()].find(x=>x.ms===10).fn();assert.deepEqual(socket.sent.map(x=>x.type),['start','audio','finish']);socket.message({type:'complete',stream_id:micOrigin.stream_id,revision:0,text:'',had_final:false});assert.deepEqual(await final,{text:'',had_final:false});assert.equal(timers.size,0);});
test('microphone disconnect after ready rejects completion immediately and cannot accept more PCM',async()=>{const socket=new Socket(),api=transport(undefined,()=>socket);const mic=api.microphone(micOrigin,signal());socket.open();socket.message({type:'ready',...micOrigin});await mic.ready;const rejected=assert.rejects(mic.completion,/disconnected/);socket.onclose();await rejected;assert.equal(socket.closed,true);assert.throws(()=>mic.send(chunk()));});
test('speech close aborts fetch and suppresses an uncooperative late response',async()=>{let resolve,request;const responseReady=new Promise(r=>resolve=r),got=[];const api=transport(async(_u,options)=>{request=options;return responseReady;});const run=api.speech(origin,signal(),pcm=>got.push(pcm));const rejected=assert.rejects(run,/cancelled/);api.close();assert.equal(request.signal.aborted,true);resolve(response([audio(),complete()]));await rejected;assert.equal(got.length,0);});
test('explicit terminal is not enough if extra packets or partial JSON follow',async()=>{for(const value of [response([audio(),complete(),audio({sequence:2,first_sample:2})]),new Response(JSON.stringify(audio())+'\n'+JSON.stringify(complete()),{headers:{'content-type':'application/x-ndjson'}})]){const api=transport(async()=>value);await assert.rejects(api.speech(origin,signal(),()=>{}));}});
test('microphone startup backlog is paced one PCM chunk per capture duration',async()=>{const socket=new Socket(),timers=new Map();let id=0,now=0;const api=transport(undefined,()=>socket,{now:()=>now,setTimeout:(fn,ms)=>{timers.set(++id,{fn,ms});return id;},clearTimeout:id=>timers.delete(id)});const mic=api.microphone(micOrigin,signal());for(let i=0;i<12;i++)mic.send({pcm16le:new Uint8Array(640),sampleRate:16000,channels:1,sequence:i,startSample:i*320,endSample:(i+1)*320});socket.open();socket.message({type:'ready',...micOrigin});await mic.ready;assert.equal(socket.sent.filter(x=>x.type==='audio').length,1);const final=mic.finish();for(let i=1;i<12;i++){const timer=[...timers.entries()].find(([_id,x])=>x.ms<1000);assert.ok(timer);timers.delete(timer[0]);now+=timer[1].ms;timer[1].fn();assert.equal(socket.sent.filter(x=>x.type==='audio').length,i+1);}assert.equal(socket.sent.at(-1).type,'finish');socket.message({type:'complete',stream_id:micOrigin.stream_id,revision:0,text:'',had_final:false});await final;assert.equal(timers.size,0);});
test('speech WAV headers are rejected rather than decoded as raw PCM samples',async()=>{const wav=Buffer.from('RIFF0000WAVEfmt ','ascii');const api=transport(async()=>response([audio({pcm_base64:wav.toString('base64')}),complete({total_samples:wav.length/2})]));let delivered=0;await assert.rejects(api.speech(origin,signal(),()=>delivered++));assert.equal(delivered,0);});
