"""Export FastAPI OpenAPI plus narrow DTO types. No network, server or providers.

Only this project's supported JSON-schema vocabulary is accepted. Unsupported
schema additions fail loudly; this is not a general-purpose codegen framework.
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "apps/api/src"))
from mira.config.settings import Settings
from mira.entrypoints.http.app import create_app


def ts_type(node: dict) -> str:
    if "$ref" in node:
        return node["$ref"].rsplit("/", 1)[-1]
    if "const" in node:
        return json.dumps(node["const"])
    if "enum" in node:
        return " | ".join(json.dumps(value) for value in node["enum"])
    if "anyOf" in node:
        return " | ".join(ts_type(item) for item in node["anyOf"])
    kind = node.get("type")
    if kind in {"string", "boolean", "null"}:
        return kind
    if kind in {"integer", "number"}:
        return "number"
    if kind == "array":
        return "ReadonlyArray<" + ts_type(node["items"]) + ">"
    if kind == "object":
        required = node.get("required", [])
        fields = [f'  readonly {key}{"" if key in required else "?"}: {ts_type(value)};'
                  for key, value in node.get("properties", {}).items()]
        if not fields:
            if node.get("additionalProperties") is False:
                return "Record<string, never>"
            raise ValueError("Unconstrained objects are not allowed in public DTOs.")
        return "{\n" + "\n".join(fields) + "\n}"
    raise ValueError(f"Unsupported schema vocabulary: {node}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    schema = create_app(Settings(), web_root=ROOT / ".no-web").openapi()
    types = "// Generated by tools/export_contracts.py. DO NOT EDIT.\n"
    for name, model in sorted(schema["components"]["schemas"].items()):
        types += f"export type {name} = {ts_type(model)};\n\n"
    outputs = {
        ROOT / "packages/contracts/openapi.json": json.dumps(schema, ensure_ascii=False, indent=2) + "\n",
        ROOT / "apps/web/src/shared/generated/contracts.ts": types,
    }
    for path, content in outputs.items():
        if args.check:
            if not path.is_file() or path.read_text() != content:
                raise SystemExit(f"Contract drift: {path.relative_to(ROOT)}. Run export_contracts.py.")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    print("Contract exports are consistent." if args.check else "Contract exports generated.")


if __name__ == "__main__":
    main()
